services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: book_social_network
    volumes:
      - db_data:/data/postgres    # Đổi tên reference để rõ ràng hơn
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
#  keycloak:
#    container_name: keycloak-bsn
#    image: quay.io/keycloak/keycloak:24.0.2
#    ports:
#      - 9090:8080
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    networks:
#      - spring-demo
#    command:
#      - "start-dev"
networks:
  spring-demo:
    name: bsn_network
    driver: bridge

volumes:
  db_data: # Đổi tên volume để rõ ràng hơn
    name: bsn_postgres_data    # Đặt tên đầy đủ và rõ ràng
    driver: local